### ISSUE TITLE
Installation Issue - spatstat

### ISSUE THREAD

**Issue by millicentFalls** [SantanderMetGroup/mopa#17]
Hi, I am very happy to have found your package, however, successful installation seems dependent on running a very old version of spatstat. I would like to avoid having run previous installations of spatstat if possible as I use the current version for the majority of other analysis I am doing.
Is it possible to update the code to work with spatstat 3.0-2?
Many thanks for your consideration.

**Comment by cofinoa** [comment]
Fixed with PR #19
