### ISSUE TITLE
Can't install mopa in R verison 4.1.1 - spatstat version issue 

### ISSUE THREAD

**Issue by KaleabTessera** [SantanderMetGroup/mopa#7]
I have installed version `1.64.1` of spatstat like `devtools::install_version("spatstat", version = "1.64.1",repos = "http://cran.us.r-project.org")`. When I check the version of spatstat, ` packageVersion("spatstat")` , it outputs `1.64.1` like I would expect. 

When I try to install mopa like `devtools::install_git("https://github.com/SantanderMetGroup/mopa.git",keep_outputs = TRUE)`, my version of spatstat appears to change and I get the following error: 
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘spatstat’ 2.2-0 is being loaded, but == 1.64.1 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
```
I also see this out out `spatstat (1.64-1 -> 2.2-0) [CRAN]` and ` packageVersion("spatstat")` outputs 2.2.0. 

How do I resolve this?

**Comment by cofinoa** [comment]
Fixed with PR #19
